app_file_creation_create:
    path: /create/{id}
    defaults: { _controller: 'AppBundle:File/Creation:createFile' }
    requirements:
        id: '\d+'

app_file_creation_create_without_parent:
    path: /create/
    defaults: { _controller: 'AppBundle:File/Creation:createFile' }