app_file_showing_show:
    path: /show/{id}
    defaults: { _controller: 'AppBundle:File/Showing:showFile' }
    requirements:
        id: '\d+'

app_file_showing_show_public:
    path: /public/{id}/{token}
    defaults: { _controller: 'AppBundle:File\Showing:showPublicFile' }
    requirements:
        id: '\d+'