imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/src/AppBundle/Resources/views/Page': Page
        '%kernel.project_dir%/src/AppBundle/Resources/views/Layout': Layout
    globals:
        file_business: '@app.business.file'
        facebook_id: '%facebook_id%'
        google_id: '%google_id%'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        '%mailer_user%'
        sender_name:    toto

hwi_oauth:
    firewall_names: [main]
    resource_owners:
        facebook_owners:
            type:                facebook
            client_id:           '%facebook_id%'
            client_secret:       '%facebook_secret%'
            scope:               "email"
            options:
                display: popup
        google_owners:
            type:                 google
            client_id:            '%google_id%'
            client_secret:        '%google_secret%'
            scope:                "email profile"
    fosub:
        username_iterations: 30
        properties:
            facebook_owners: facebookId
            google_owners: googleId

vich_uploader:
    db_driver: orm
    mappings:
        files:
            uri_prefix: '%url_suffix%/uploads/files'
            upload_destination: '%file_path%'
            namer: vich_uploader.namer_uniqid