app_folder_creation_create:
    path: /create/{id}
    defaults: { _controller: 'AppBundle:Folder/Creation:createFolder' }
    requirements:
        id: '\d+'

app_folder_creation_create_without_parent:
    path: /create/
    defaults: { _controller: 'AppBundle:Folder/Creation:createFolder' }